### ISSUE TITLE
Incompatible with kube-rs 0.86 and k8s-openapi 0.20

### ISSUE THREAD

**Issue by xanderdunn** [hendrikmaus/kube-leader-election#73]
Thanks for providing this very convenient crate!

I've been unable to build this crate as a dependency in my crate when using kube-rs 0.86:
```
[dependencies]
kube = { version = "0.86", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20", features = ["latest"] }
kube-leader-election = ">=0.25"
```
I haven't been able to figure out a compatible k8s-openapi configuration. However, reducing the version of `kube-rs` down to 0.85 and k8s-openapi down to 0.19 works fine.

**Comment by hendrikmaus** [comment]
That is probably because `kube-leader-election` is currently pinned at `0.19` for `k8s-openapi`. https://github.com/hendrikmaus/kube-leader-election/blob/6b61654a0c711af9e01e5bf27cfd17d1dd53e58d/Cargo.toml#L13

I do not currently have time to look into that. Would appreciate if you'd submit a pull-request with a fix.

**Comment by hendrikmaus** [comment]
Actually I am trying to make things more flexible with the upcoming release in https://github.com/hendrikmaus/kube-leader-election/pull/74

**Comment by hendrikmaus** [comment]
Ok that did not work out as wildcards aren't allowed

>Caused by:
  the remote server responded with an error: wildcard (`*`) dependency constraints are not allowed on crates.io. Crate with this problem: `k8s-openapi` See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information

**Comment by hendrikmaus** [comment]
Next approach https://github.com/hendrikmaus/kube-leader-election/pull/76

**Comment by hendrikmaus** [comment]
Seems to work out for you as well now, tested with: 
```toml
[package]
name = "kube-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0.86", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20", features = ["v1_28"] }
kube-leader-election = "0.27"
```
